import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import { SessionProvider } from 'next-auth/react'
import { auth } from '@/auth'
import '@repo/ui/globals.css'
import { Toaster } from "@repo/ui/components/sonner";

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  const session = await auth();

  return (
    <SessionProvider session={session}>
      <html lang="en">
        <body className={inter.className}>
          <Toaster
            toastOptions={{
              unstyled: false,
              classNames: {
                success: "text-green-800"
              }
            }}
            position='bottom-center' />
          {children}
        </body>
      </html>
    </SessionProvider>
  )
}
