version: "3"

volumes:
  database:
    driver: local

services:
  main:
    container_name: main
    build:
      args:
        NEXT_PUBLIC_PADDLE_CLIENT_KEY: ${NEXT_PUBLIC_PADDLE_CLIENT_KEY}
        NEXT_PUBLIC_PADDLE_ENV: ${NEXT_PUBLIC_PADDLE_ENV}
        NEXT_PUBLIC_RECAPTCHA_SITE_KEY: ${NEXT_PUBLIC_RECAPTCHA_SITE_KEY}
        NEXT_PUBLIC_APP_URL: ${NEXT_PUBLIC_APP_URL}
        NEXT_PUBLIC_CLIENT_URL: ${NEXT_PUBLIC_CLIENT_URL}
      context: .
      dockerfile: ./apps/main/Dockerfile
    restart: always
    ports:
      - 3000:3000
    dns:
      - 8.8.8.8
      - 1.1.1.1
    environment:
      - NEXT_PUBLIC_PADDLE_CLIENT_KEY=${NEXT_PUBLIC_PADDLE_CLIENT_KEY}
      - NEXT_PUBLIC_PADDLE_ENV=${NEXT_PUBLIC_PADDLE_ENV}
      - NEXT_PUBLIC_APP_URL=${NEXT_PUBLIC_APP_URL}
      - NEXT_PUBLIC_API_URL=${NEXT_PUBLIC_API_URL}
      - NEXT_PUBLIC_CLIENT_URL=${NEXT_PUBLIC_CLIENT_URL}
    networks:
      - app_network
    depends_on:
      - migration

  client:
    container_name: client
    build:
      args:
        NEXT_PUBLIC_PADDLE_CLIENT_KEY: ${NEXT_PUBLIC_PADDLE_CLIENT_KEY}
        NEXT_PUBLIC_PADDLE_ENV: ${NEXT_PUBLIC_PADDLE_ENV}
        NEXT_PUBLIC_RECAPTCHA_SITE_KEY: ${NEXT_PUBLIC_RECAPTCHA_SITE_KEY}
        NEXT_PUBLIC_APP_URL: ${NEXT_PUBLIC_APP_URL}
        NEXT_PUBLIC_CLIENT_URL: ${NEXT_PUBLIC_CLIENT_URL}
      context: .
      dockerfile: ./apps/client/Dockerfile
    restart: always
    ports:
      - 3001:3001
    environment:
      - NEXT_PUBLIC_PADDLE_CLIENT_KEY=${NEXT_PUBLIC_PADDLE_CLIENT_KEY}
      - NEXT_PUBLIC_PADDLE_ENV=${NEXT_PUBLIC_PADDLE_ENV}
      - NEXT_PUBLIC_APP_URL=${NEXT_PUBLIC_APP_URL}
      - NEXT_PUBLIC_API_URL=${NEXT_PUBLIC_API_URL}
      - NEXT_PUBLIC_CLIENT_URL=${NEXT_PUBLIC_CLIENT_URL}
    dns:
      - 8.8.8.8
      - 1.1.1.1
    labels:
      - traefik.enable=true

      # HTTP redirect to HTTPS
      - traefik.http.routers.client-main-http.rule=Host(`requro.com`)
      - traefik.http.routers.client-main-http.entrypoints=http
      - traefik.http.routers.client-main-http.middlewares=redirect-to-https

      - traefik.http.routers.client-wildcard-http.rule=HostRegexp(`^.+\\.requro\\.com$`)
      - traefik.http.routers.client-wildcard-http.entrypoints=http
      - traefik.http.routers.client-wildcard-http.middlewares=redirect-to-https

      # HTTPS routers
      - traefik.http.routers.client-main-https.rule=Host(`requro.com`)
      - traefik.http.routers.client-main-https.entrypoints=https
      - traefik.http.routers.client-main-https.tls=true
      - traefik.http.routers.client-main-https.tls.certresolver=letsencrypt
      - traefik.http.routers.client-main-https.middlewares=gzip

      - traefik.http.routers.client-wildcard-https.rule=HostRegexp(`^.+\\.requro\\.com$`)
      - traefik.http.routers.client-wildcard-https.entrypoints=https
      - traefik.http.routers.client-wildcard-https.tls=true
      - traefik.http.routers.client-wildcard-https.tls.certresolver=letsencrypt
      - traefik.http.routers.client-wildcard-https.middlewares=gzip

      # Middlewares
      - traefik.http.middlewares.gzip.compress=true
      - traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https

      # Service Definition
      - traefik.http.services.client.loadbalancer.server.port=3001
    networks:
      - app_network
    depends_on:
      - migration

  migration:
    container_name: migration
    build:
      context: .
      dockerfile: ./Dockerfile.migrate
    environment:
      - NODE_ENV=production
    networks:
      - app_network
    command: ["pnpm", "run", "db:migrate:deploy"]

networks:
  app_network:
    driver: bridge
