version: "3"

volumes:
  database:
    driver: local

services:
  main:
    container_name: main
    build:
      args:
        NEXT_PUBLIC_PADDLE_CLIENT_KEY: ${NEXT_PUBLIC_PADDLE_CLIENT_KEY}
        NEXT_PUBLIC_PADDLE_ENV: ${NEXT_PUBLIC_PADDLE_ENV}
        NEXT_PUBLIC_RECAPTCHA_SITE_KEY: ${NEXT_PUBLIC_RECAPTCHA_SITE_KEY}
        NEXT_PUBLIC_APP_URL: ${NEXT_PUBLIC_APP_URL}
        NEXT_PUBLIC_CLIENT_URL: ${NEXT_PUBLIC_CLIENT_URL}
      context: .
      dockerfile: ./apps/main/Dockerfile
    restart: always
    ports:
      - 3000:3000
    dns:
      - 8.8.8.8
      - 1.1.1.1
    environment:
      - NEXT_PUBLIC_PADDLE_CLIENT_KEY=${NEXT_PUBLIC_PADDLE_CLIENT_KEY}
      - NEXT_PUBLIC_PADDLE_ENV=${NEXT_PUBLIC_PADDLE_ENV}
      - NEXT_PUBLIC_APP_URL=${NEXT_PUBLIC_APP_URL}
      - NEXT_PUBLIC_API_URL=${NEXT_PUBLIC_API_URL}
      - NEXT_PUBLIC_CLIENT_URL=${NEXT_PUBLIC_CLIENT_URL}
    networks:
      - app_network
    depends_on:
      - migration

  client:
    container_name: client
    build:
      args:
        NEXT_PUBLIC_PADDLE_CLIENT_KEY: ${NEXT_PUBLIC_PADDLE_CLIENT_KEY}
        NEXT_PUBLIC_PADDLE_ENV: ${NEXT_PUBLIC_PADDLE_ENV}
        NEXT_PUBLIC_RECAPTCHA_SITE_KEY: ${NEXT_PUBLIC_RECAPTCHA_SITE_KEY}
        NEXT_PUBLIC_APP_URL: ${NEXT_PUBLIC_APP_URL}
        NEXT_PUBLIC_CLIENT_URL: ${NEXT_PUBLIC_CLIENT_URL}
      context: .
      dockerfile: ./apps/client/Dockerfile
    restart: always
    ports:
      - 3001:3001
    environment:
      - NEXT_PUBLIC_PADDLE_CLIENT_KEY=${NEXT_PUBLIC_PADDLE_CLIENT_KEY}
      - NEXT_PUBLIC_PADDLE_ENV=${NEXT_PUBLIC_PADDLE_ENV}
      - NEXT_PUBLIC_APP_URL=${NEXT_PUBLIC_APP_URL}
      - NEXT_PUBLIC_API_URL=${NEXT_PUBLIC_API_URL}
      - NEXT_PUBLIC_CLIENT_URL=${NEXT_PUBLIC_CLIENT_URL}
    dns:
      - 8.8.8.8
      - 1.1.1.1
    labels:
      - traefik.enable=true
      - traefik.http.routers.client-router-https.rule=HostRegexp(`^.+\.requro\.com$`)
      - traefik.http.routers.client-router-https.priority=0
      - traefik.http.routers.client-router-https.entryPoints=https
      - traefik.http.routers.client-router-https.tls=true
      - traefik.http.routers.client-router-https.tls.certresolver=letsencrypt
      - traefik.http.routers.client-router-https.middlewares=gzip
      - traefik.http.routers.client-router-https.service=client-service

       # HTTP Router (for redirecting to HTTPS)
      - traefik.http.routers.client-router-http.rule=HostRegexp(`^.+\.requro\.com$`)
      - traefik.http.routers.client-router-http.priority=0
      - traefik.http.routers.client-router-http.entryPoints=http
      - traefik.http.routers.client-router-http.middlewares=redirect-to-https

       # Define HTTPS Middleware (Compression)
      - traefik.http.middlewares.gzip.compress=true

       # Define HTTP to HTTPS Redirection Middleware
      - traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https

      # Service Definition
      - traefik.http.services.client-service.loadbalancer.server.port=3001

      - caddy_0.encode=zstd gzip
      - caddy_0.handle_path.0_reverse_proxy={{upstreams 3001}}
      - caddy_0.handle_path=*
      - caddy_0.header=-Server
      - caddy_0.try_files={path} /index.html /index.php
      - caddy_0=://
      - caddy_ingress_network=app_network

    networks:
      - app_network
    depends_on:
      - migration

  migration:
    container_name: migration
    build:
      context: .
      dockerfile: ./Dockerfile.migrate
    environment:
      - NODE_ENV=production
    networks:
      - app_network
    command: ["pnpm", "run", "db:migrate:deploy"]

networks:
  app_network:
    driver: bridge
