version: "3"

volumes:
  database:
    driver: local

services:
  main:
    container_name: main
    build:
      context: .
      dockerfile: ./apps/main/Dockerfile
    restart: always
    ports:
      - 3000:3000
    dns:
      - 8.8.8.8
      - 1.1.1.1
    environment:
      - NEXT_PUBLIC_PADDLE_CLIENT_KEY=${NEXT_PUBLIC_PADDLE_CLIENT_KEY}
      - NEXT_PUBLIC_PADDLE_ENV=${NEXT_PUBLIC_PADDLE_ENV}
      - NEXT_PUBLIC_APP_URL=${NEXT_PUBLIC_APP_URL}
      - NEXT_PUBLIC_API_URL=${NEXT_PUBLIC_API_URL}
      - NEXT_PUBLIC_CLIENT_URL=${NEXT_PUBLIC_CLIENT_URL}
    networks:
      - app_network
    depends_on:
      - migration  # Ensures migrations run before the main service

  client:
    container_name: client
    build:
      context: .
      dockerfile: ./apps/client/Dockerfile
    restart: always
    ports:
      - 3001:3001
    dns:
      - 8.8.8.8
      - 1.1.1.1
    networks:
      - app_network
    depends_on:
      - migration  # Ensures migrations run before the client service

  migration:
    container_name: migration
    build:
      context: .
      dockerfile: ./Dockerfile.migrate  # Points to the migration Dockerfile
    environment:
      - NODE_ENV=production  # Set this as needed
    networks:
      - app_network
    command: ["pnpm", "run", "db:migrate:deploy"]  # This will run the Prisma migrations on container startup

networks:
  app_network:
    driver: bridge

