version: "3.8"

services:
  # Your existing services
  main:
    container_name: main
    build:
      context: .
      dockerfile: ./apps/main/Dockerfile
    depends_on:
      - database-migrations  # Wait for migrations to complete
    environment:
      DATABASE_URL: ${DATABASE_URL}
    ports:
      - 3000:3000
    networks:
      - app_network

  client:
    container_name: client
    build:
      context: .
      dockerfile: ./apps/client/Dockerfile
    depends_on:
      - database-migrations  # Wait for migrations to complete
    environment:
      DATABASE_URL: ${DATABASE_URL}
    ports:
      - 3001:3001
    networks:
      - app_network

  # New migration service
  # database-migrations:
  #   build:
  #     context: .  # Point to monorepo root
  #     dockerfile: ./packages/database/Dockerfile
  #   environment:
  #     DATABASE_URL: ${DATABASE_URL}

networks:
  app_network:
    driver: bridge